# Generated by Django 5.0.2 on 2024-03-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moscip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scout',
            name='gender',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
